return {
    cmd = { "emmet-ls", "--stdio" },
    filetypes = {
        "blade",
        "astro",
        "css",
        "eruby",
        "html",
        "htmldjango",
        "javascriptreact",
        "less",
        "pug",
        "sass",
        "scss",
        "svelte",
        "typescriptreact",
        "vue",
        "htmlangular",
    },
    root_markers = { ".git" },
}
